## 
## BASH RC - every new shell
## 

if [ -d "$HOME/.bashrc.d" ]; then
	for script in $(find "$HOME/.bashrc.d/" -name '*.sh' |sort -n) ; do
		# echo "Loading `basename \"$script\"`..." # >&2
		. $script
	done
fi


